version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python api/manage.py wait_for_db &&
             python api/manage.py migrate &&
             python api/manage.py runserver 0.0.0.0:8000"
    environment:
      # local instance
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=somepassword
      # AWS RDS Instance
      # - DB_HOST=postgresqlinstanceidentifier.c1604jszeu6w.eu-central-1.rds.amazonaws.com
      # - DB_NAME=PostgreSQLDBInstance_API_Models_Framework
      # - DB_USER=postgres
      # - DB_PASS=mypostgrespassword
    depends_on:
      - db

  # Testing database, the production one is on AWS
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
