version: 2
jobs:
  test_regression_model:
    working_directory: ~/src/models/regression_model
    docker:
      image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
