version: 2
jobs:
  train_and_test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/models/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
      - run:
          name: Train the model
          command: |
            source venv/bin/activate
            PYTHONPATH=src/models/regression_model python3 src/models/regression_model/regression_model/train_pipeline.py
      - run:
          name: Test the model
          command: |
            source venv/bin/activate
            py.test -vv src/models/regression_model/tests
  publish_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/models/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
      - run:
          name: Train aund publish the model
          command: |
            source venv/bin/activate
            PYTHONPATH=src/models/regression_model python3 src/models/regression_model/regression_model/train_pipeline.py
            ./scripts/publish_model.sh src/models/regression_model
workflows:
  version: 2
  test-and-publish-regression-model:
    jobs:
      - train_and_test_regression_model
      - publish_regression_model:
          requires:
            - train_and_test_regression_model
