version: 2
jobs:
  test_data_science_module:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/data_science/requirements.txt
      - run:
          name: Test the module
          command: |
            source venv/bin/activate
            python3 src/data_science/tests/tests.py
  publish_data_science_module:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/data_science/requirements.txt
      - run:
          name: Publish the Module
          command: |
            source venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh src/data_science
  train_and_test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/models/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
      - run:
          name: Train the model
          command: |
            source venv/bin/activate
            PYTHONPATH=src/models/regression_model python3 src/models/regression_model/regression_model/train_pipeline.py
      - run:
          name: Test the model
          command: |
            source venv/bin/activate
            py.test -vv src/models/regression_model/tests
  publish_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/models/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
      - run:
          name: Train and publish the model
          command: |
            source venv/bin/activate
            PYTHONPATH=src/models/regression_model python3 src/models/regression_model/regression_model/train_pipeline.py
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh src/models/regression_model
  test_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/api/requirements.txt
      - run:
          name: Test the api
          command: |
            source venv/bin/activate
            PYTHONPATH=src/api python3 src/api/manage.py test api
            flake8 api
workflows:
  version: 2
  test-and-publish-data-science-module:
    jobs:
      - test_data_science_module
      - publish_data_science_module:
          requires:
            - test_data_science_module
          filters:
            branches:
              only:
                - master
  test-and-publish-regression-model:
    jobs:
      - train_and_test_regression_model
      - publish_regression_model:
          requires:
            - train_and_test_regression_model
          filters:
            branches:
              only:
                - master
  test-and-publish-api:
    jobs:
      - test_api

