version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r src/models/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv src/models/regression_model/tests

  train_and_upload_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: 
          name: Setup env
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r src/models/regression_model/requirements.txt
      - run: 
          name: Publish model
          command: |
            source venv/bin/activate
            chmod +x ./scripts/fetch_kaggle_dataset.sh ./scripts/publish_model.sh
            ./scripts/fetch_kaggle_dataset.sh
            PYTHONPATH=src/models/regression_model python3 src/models/regression_model/regression_model/train_pipeline.py
            ./scripts/publish_model.sh src/models/regression_model
workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
      - train_and_upload_regression_model